### ISSUE TITLE
No permissions in forge singleplayer

### ISSUE THREAD

**Issue by Quarg** [TVPT/VoxelSniper#283]
When I try to use any commands added by VoxelSniper, I get the message "&4You require permission in order to perfom this command", and I cannot find how to set permissions.

I am using Forge, and have both VoxelSniper-7.1.0-SNAPSHOT.jar and VoxelGunsmith-7.1.0-SNAPSHOT.jar in my mods folder.

**Comment by oneill011990** [comment]
Same issue here, using VS build 420. Forge 11.15.1.1744 on MC 1.8.9.
Downloaded the *-all.jar 
No error appear in the logs, just the chat notification.

**Comment by frankieg06** [comment]
same here,
just found vs for sp and im disapointed

**Comment by gabizou** [comment]
Just to note that VS 7 probably works best with SpongeForge installed for single player. That being said, it's not likely that it'll be fixed in the next few days as both @Deamon5550 and myself are busy with other higher priority projects and IRL projects.

**Comment by Deamon5550** [comment]
The forge version is no longer supported, the sponge version should work fine in single player with spongeforge installed however, any permission problems that still exist would be the fault of sponge (but I doubt there are any)
